name: ne
favicon: null
layout_spectrum: 0.819708356866613
typography_spectrum: 0.45757975918240845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12801341665908694
  lightness: 0.07373921270482242
  saturation: 0.39557086140848696
  rhythmicContrast: 0.12660587998107076
purpose: []
